const ProjectsData = [
  {
    name: "KinderLink Dashboard",
    lang: "React js",
    imgSrc: "assets/projects_images/kinderLink_Dashboard.png",
    codeSrc: "https://github.com/Abdo-Atef/Daycare-dashboard",
    benaceSrc: "https://www.behance.net/gallery/202417727/Kinder-Link-Dashboard",
    youtubeSrc: "https://youtu.be/tWICZ91ybsw?si=Tk_jONNxOLTh1ypG",
    createdAt: "07/2024",
  },
  {
    name: "KinderLink App (Mobile App)",
    lang: "React Native",
    imgSrc: "assets/projects_images/kinderLink_app.png",
    codeSrc: "https://github.com/Abdo-Atef/Daycare-dashboard",
    benaceSrc: "https://www.behance.net/gallery/202515891/Kinder-Link-Mobile-App",
    youtubeSrc: "https://youtu.be/tWICZ91ybsw?si=Tk_jONNxOLTh1ypG",
    createdAt: "07/2024",
  },
  {
    name: "Exclusive E-commerce",
    lang: "React js",
    imgSrc: "assets/projects_images/Exclusive.webp",
    codeSrc: "https://github.com/Abdo-Atef/Exclusive",
    hostSrc: "https://exclusive-store1.vercel.app",
    createdAt: "03/2024",
  },
  {
    name: "Pharmacy management system",
    lang: "React js",
    imgSrc: "assets/projects_images/Pharmacy.webp",
    codeSrc:"https://github.com/Abdo-Atef/Pharmacy-inventory-management-system",
    youtubeSrc: "https://www.youtube.com/watch?v=T1TxiPJPPQg",
    createdAt: "12/2023",
  },
  {
    name: "Movix",
    lang: "Next.js, Typescript, Tailwind",
    imgSrc: "assets/projects_images/movix.webp",
    codeSrc: "https://github.com/Abdo-Atef/Movix",
    hostSrc: "https://movix1.vercel.app/",
    createdAt: "08/2024",
  },
  {
    name: "lott ag",
    lang: "Next.js, Typescript, Tailwind",
    imgSrc: "assets/projects_images/lott_ag.jpeg",
    hostSrc: "https://lott-ag-website.vercel.app/",
    createdAt: "03/2025",
  },
  {
    name: "makamarble",
    lang: "Next.js, Typescript, Tailwind",
    imgSrc: "assets/projects_images/makamarble.jpeg",
    hostSrc: "https://maka-marble.vercel.app/",
    createdAt: "11/2024",
  },
    {
    name: "Hemma-Itqan",
    lang: "Next.js, Typescript, Tailwind",
    imgSrc: "assets/projects_images/hemma-itqan.webp",
    hostSrc: "https://hemma-itqan.com/",
    createdAt: "03/2026",
  },
    {
    name: "Batsync",
    lang: "Next.js, Typescript, Tailwind",
    imgSrc: "assets/projects_images/batsync.webp",
    hostSrc: "https://batsync-dev.vercel.app/",
    createdAt: "11/2024",
  },
  {
    name: "Induz",
    lang: "React js, Tailwind",
    imgSrc: "assets/projects_images/Induz.webp",
    codeSrc: "https://github.com/Abdo-Atef/Induz",
    hostSrc: "https://induz-ten.vercel.app/",
    createdAt: "06/2024",
  },
  {
    name: "Notion",
    lang: "React Native, firebase",
    imgSrc: "assets/projects_images/Notion.webp",
    codeSrc: "https://github.com/Abdo-Atef/Notion",
    createdAt: "03/2024",
  },
  {
    name: "AbdoFolio",
    lang: "HTML, CSS",
    imgSrc: "assets/projects_images/AbdoFolio.webp",
    codeSrc: "https://github.com/Abdo-Atef/AbdoFolio",
    hostSrc: "https://abdo-atef.github.io/AbdoFolio/",
    createdAt: "04/2023",
  },
    {
    name: "khosomatk",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/khosomatk.webp",
    hostSrc: "https://abdo-atef.github.io/khosomatk",
    codeSrc: "https://github.com/Abdo-Atef/khosomatk",
    createdAt: "06/2024",
  },
  {
    name: "Simple Dashboard",
    lang: "HTML, CSS",
    imgSrc: "assets/projects_images/Dashboard.webp",
    codeSrc: "https://github.com/Abdo-Atef/Dashboard",
    hostSrc: "https://abdo-atef.github.io/Dashboard/",
    createdAt: "05/2023",
  },
  {
    name: "DevFolio",
    lang: "HTML, CSS, Bootstrap",
    imgSrc: "assets/projects_images/DevFolio.webp",
    codeSrc: "https://github.com/Abdo-Atef/DevFolio",
    hostSrc: "https://abdo-atef.github.io/DevFolio/",
    createdAt: "06/2023",
  },
  {
    name: "Danials",
    lang: "HTML, CSS, Bootstrap",
    imgSrc: "assets/projects_images/Danials.webp",
    codeSrc: "https://github.com/Abdo-Atef/Danials",
    hostSrc: "https://abdo-atef.github.io/Danials/",
    createdAt: "07/2023",
  },
  {
    name: "Games Website",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/Game.webp",
    codeSrc: "https://github.com/Abdo-Atef/Game-oop",
    hostSrc: "https://abdo-atef.github.io/Game-oop/",
    createdAt: "08/2023",
  },
  {
    name: "To-Do-List App",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/Todo.webp",
    codeSrc: "https://github.com/Abdo-Atef/To-Do-List",
    hostSrc: "https://abdo-atef.github.io/To-Do-List/",
    createdAt: "09/2023",
  },
  {
    name: "Yummy",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/yummy.webp",
    codeSrc: "https://github.com/Abdo-Atef/Yummy",
    hostSrc: "https://abdo-atef.github.io/Yummy/",
    createdAt: "11/2023",
  },
  {
    name: "Quiz App",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/Quiz.webp",
    codeSrc: "https://github.com/Abdo-Atef/Quiz-App",
    hostSrc: "https://abdo-atef.github.io/Quiz-App/",
    createdAt: "09/2023",
  },
  {
    name: "Bookmark App",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/Bookmark.webp",
    codeSrc: "https://github.com/Abdo-Atef/Bookmark",
    hostSrc: "https://abdo-atef.github.io/Bookmark/",
    createdAt: "11/2023",
  },
  {
    name: "Weather App",
    lang: "HTML, CSS, JS",
    imgSrc: "assets/projects_images/Weather.webp",
    codeSrc: "https://github.com/Abdo-Atef/Weather-Project",
    hostSrc: "https://abdo-atef.github.io/Weather-Project/",
    createdAt: "08/2023",
  },
  {
    name: "NFT_MarketPlace",
    lang: "React Native",
    imgSrc: "assets/projects_images/NFT.webp",
    codeSrc: "https://github.com/Abdo-Atef/NFT_MarketPlace",
    createdAt: "02/2024",
  },
  {
    name: "Kasper",
    lang: "HTML, CSS",
    imgSrc: "assets/projects_images/Kasper.webp",
    codeSrc: "https://github.com/Abdo-Atef/Kasper",
    hostSrc: "https://abdo-atef.github.io/Kasper/",
    createdAt: "04/2023",
  },
  {
    name: "Leon",
    lang: "HTML, CSS",
    imgSrc: "assets/projects_images/Leon.webp",
    codeSrc: "https://github.com/Abdo-Atef/Leon",
    hostSrc: "https://abdo-atef.github.io/Leon/",
    createdAt: "03/2023",
  },
];